---
#
## Browbeat's NFV Install
##

# this playbook will reboot the target machine, can't run it if playbook is executed from localhost
- fail:
    msg: "system need reboot but this playbook is running from localhosti, please rerun from a remote machine"
  when: inventory_hostname == "localhost"

- name: pbench internal repo
  shell: |
    sudo wget -O /etc/yum.repos.d/pbench-internal.repo "{{ pbench_internal_url }}"
  when: pbench_internal_url is defined
  become: true

- name: pbench redhat internal repo
  copy:
    src: files/pbench-internal.repo
    dest: /etc/yum.repos.d/pbench-internal.repo
    owner: root
    group: root
  when: pbench_internal_url is not defined
  become: true

- name: pbench external repo
  copy:
    src: files/pbench-external.repo
    dest: /etc/yum.repos.d/pbench-external.repo
    owner: root
    group: root
  become: true
- name: install optional repo
  copy: 
    src: files/rhel-optional.repo
    dest: /etc/yum.repos.d/rhel-optional.repo
    owner: root
    group: root
  become: true

- name: install pbench
  yum: name={{ item }}
  with_items:
    - pbench-agent
    - pbench-agent-internal
    - pbench-sysstat
  become: true

- name: copy pbench-trafficgen files
  shell: |
    wget -O /opt/pbench-agent/bench-scripts/pbench-trafficgen https://raw.githubusercontent.com/atheurer/pbench/trafficgen/agent/bench-scripts/pbench-trafficgen 
    wget -O /opt/pbench-agent/bench-scripts/postprocess/trafficgen-postprocess https://raw.githubusercontent.com/atheurer/pbench/trafficgen/agent/bench-scripts/postprocess/trafficgen-postprocess 
  become: true

- name: remove existing nfv directory to have a fresh start
  shell: |
    rm -rf "{{nfv_dir}}" 2>/dev/null
  ignore_errors: yes
- name: Create nfv directory 
  git: 
    repo: "{{nfv_git_url}}"
    dest: "{{nfv_dir}}"
    accept_hostkey: yes

- name: fixup overcloudrc in nfv_test.cfg file
  lineinfile:
    name: "{{nfv_dir}}/nfv_test.cfg"
    regexp: '^overcloudrc'
    line: "overcloudrc={{overcloudrc}}"

- name: fixup stackrc in nfv_test.cfg  
  lineinfile:
    name: "{{nfv_dir}}/nfv_test.cfg"
    regexp: '^stackrc'
    line: "stackrc={{home_dir}}/stackrc"
- name: fixup nfv_tmp_dir in nfv_test.cfg
  lineinfile:
    name: "{{nfv_dir}}/nfv_test.cfg"
    regexp: '^nfv_tmp_dir'
    line: "nfv_tmp_dir={{nfv_dir}}/tmp"

- name: Deploy VM access vlan interface
  template:
    src: templates/ifcfg-vm-access.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{nfv_vm_access_device}}"
    owner: root
    group: root
  become: true

- name: Turn on vm access vlan interface
  shell: ifup {{nfv_vm_access_device}}
  become: true

- name: Deploy Private external vlan interface
  template:
    src: templates/ifcfg-vlan.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{nfv_external_vlan_device}}"
    owner: root
    group: root
  become: true

- name: Turn on Private external vlan interface
  shell: ifup {{nfv_external_vlan_device}}
  become: true

- name: check SNAT entry
  shell: iptables -t nat -L POSTROUTING | egrep "MASQUERADE.*anywhere.*anywhere"
  register: testsnat
  failed_when: testsnat.stderr != ""
  become: true

- name: setup snat for VM if not done
  shell: |
    echo 1 > /proc/sys/net/ipv4/ip_forward
    oif=$(ip route | grep default | awk '{print $5}')
    iptables -t nat -A POSTROUTING -o $oif -j MASQUERADE
    /sbin/service iptables save
  when: testsnat.rc == 1
  become: true

- name: install rhelosp-rhel-7-fast-datapth.repo
  copy: src=files/rhelosp-rhel-7-fast-datapth.repo dest=/etc/yum.repos.d/rhelosp-rhel-7-fast-datapth.repo owner=root group=root mode=0644
  become: true

- name: update tuned and isolcpu boot parameter
  shell: |
    yum install -y dpdk
    yum install -y dpdk-tools
    yum -y install libhugetlbfs-utils
    hugeadm --create-global-mounts
    yum remove -y tuned
    yum install -y tuned
    yum install -y tuned-profiles-cpu-partitioning
    nic1_numa=$(cat /sys/class/net/{{trafficgen_nic1}}/device/numa_node)
    if [[ ${nic1_numa} -eq 0 ]]; then
      core1=2
    else
      core1=1
    fi
    nic2_numa=$(cat /sys/class/net/{{trafficgen_nic2}}/device/numa_node)
    if [[ ${nic2_numa} -eq 0 ]]; then
      core2=4
    else
      core2=3
    fi
    grubby --update-kernel=`grubby --default-kernel` --args="default_hugepagesz=1G hugepagesz=1G hugepages=8 isolcpus=$core1,$core2 intel_iommu=on iommu=pt"
    sed -i -r '^isolated_cores/d' /etc/tuned/cpu-partitioning-variables.conf
    echo isolated_cores=$core1,$core2 >> /etc/tuned/cpu-partitioning-variables.conf
    tuned-adm profile cpu-partitioning
  become: true

- name: Reboot machine
  shell: "nohup sh -c '( sleep 5 ; shutdown -r now )' &"
  async: 0
  poll: 0
  ignore_errors: true
  become: true

# 8 minute timeout
- name: Wait for Machine Ready
  local_action:
    module: wait_for
    host: "{{inventory_hostname}}"
    port: 22
    delay: 60
    timeout: 480

# after reboot, traffic-gen ports become kernel ports, get the pci-slot from the int name
- name: Get traffic-gen port bus info
  shell: |
    traffic_gen_src_slot=$(ethtool -i {{trafficgen_nic1}} | grep "bus-info:" | awk '{print $2}')
    traffic_gen_dst_slot=$(ethtool -i {{trafficgen_nic2}} | grep "bus-info:" | awk '{print $2}')
    sed -i -r "s/^traffic_gen_src_slot=.*/traffic_gen_src_slot=${traffic_gen_src_slot}/" {{nfv_dir}}/nfv_test.cfg
    sed -i -r "s/^traffic_gen_dst_slot=.*/traffic_gen_dst_slot=${traffic_gen_dst_slot}/" {{nfv_dir}}/nfv_test.cfg
  become: true

