# This is the playbook used by the `quickstart.sh` script.

- include: quickstart-extras.yml

- name: Configure Browbeat
  hosts: undercloud
  roles:
    - browbeat/pre-install-setup
    - browbeat/oooq-metadata

- name: Install Browbeat
  hosts: undercloud
  vars:
    results_in_httpd: false
  roles:
    - browbeat/common
    - browbeat/browbeat
    - browbeat/browbeat-results
    - browbeat/firewall
    - browbeat/perfkitbenchmarker
    - browbeat/rally
    - browbeat/shaker
    - browbeat/yoda
    - browbeat/flavors
    - browbeat/images
    - browbeat/browbeat-network
    - browbeat/template-configs

- name: Run Browbeat
  hosts: undercloud
  roles:
    - browbeat/collectd
    - browbeat/bug-check
    - browbeat/browbeat-run
