---
#
# Tasks to check requirements for installing shaker
#

- name: Check for heat
  service: name={{ item }} state=started
  become: true
  with_items:
   - openstack-heat-api
   - openstack-heat-engine
